#include "utils.hpp"

std::string camelCase(std::string const& input)
{
    std::string s; s.reserve(input.length());
    bool isMakeUpper = false;

    for(char c : input)
    {
        if(c == '_')
            isMakeUpper = true;
        else if(isMakeUpper)
            s += (char)toupper(c), isMakeUpper = false;
        else
            s += c;
    }

    return s;
}

std::string getColorSpaceId(int colorSpace)
{
	switch(colorSpace)
	{
		case AVCOL_SPC_RGB: return "RGB";
		case AVCOL_SPC_BT709: return "BT709";
		case AVCOL_SPC_UNSPECIFIED: return "UNSPECIFIED";
		case AVCOL_SPC_RESERVED: return "RESERVED";
		case AVCOL_SPC_FCC: return "FCC";
		case AVCOL_SPC_BT470BG: return "BT470BG";
		case AVCOL_SPC_SMPTE170M: return "SMPTE170M";
		case AVCOL_SPC_SMPTE240M: return "SMPTE240M";
		case AVCOL_SPC_YCOCG: return "YCOCG";
		case AVCOL_SPC_BT2020_NCL: return "BT2020_NCL";
		case AVCOL_SPC_BT2020_CL: return "BT2020_CL";
		case AVCOL_SPC_NB: return "NB";
		default: return "UNKNOW";
	}
}

std::string channelLayoutId(int layoutId)
{
	if (layoutId == AV_CH_FRONT_LEFT) return "FRONT_LEFT";
	if (layoutId == AV_CH_FRONT_RIGHT) return "FRONT_RIGHT";
	if (layoutId == AV_CH_FRONT_CENTER) return "FRONT_CENTER";
	if (layoutId == AV_CH_LOW_FREQUENCY) return "LOW_FREQUENCY";
	if (layoutId == AV_CH_BACK_LEFT) return "BACK_LEFT";
	if (layoutId == AV_CH_BACK_RIGHT) return "BACK_RIGHT";
	if (layoutId == AV_CH_FRONT_LEFT_OF_CENTER) return "FRONT_LEFT_OF_CENTER";
	if (layoutId == AV_CH_FRONT_RIGHT_OF_CENTER) return "FRONT_RIGHT_OF_CENTER";
	if (layoutId == AV_CH_BACK_CENTER) return "BACK_CENTER";
	if (layoutId == AV_CH_SIDE_LEFT) return "SIDE_LEFT";
	if (layoutId == AV_CH_SIDE_RIGHT) return "SIDE_RIGHT";
	if (layoutId == AV_CH_TOP_CENTER) return "TOP_CENTER";
	if (layoutId == AV_CH_TOP_FRONT_LEFT) return "TOP_FRONT_LEFT";
	if (layoutId == AV_CH_TOP_FRONT_CENTER) return "TOP_FRONT_CENTER";
	if (layoutId == AV_CH_TOP_FRONT_RIGHT) return "TOP_FRONT_RIGHT";
	if (layoutId == AV_CH_TOP_BACK_LEFT) return "TOP_BACK_LEFT";
	if (layoutId == AV_CH_TOP_BACK_CENTER) return "TOP_BACK_CENTER";
	if (layoutId == AV_CH_TOP_BACK_RIGHT) return "TOP_BACK_RIGHT";
	if (layoutId == AV_CH_STEREO_LEFT) return "STEREO_LEFT";
	if (layoutId == AV_CH_STEREO_RIGHT) return "STEREO_RIGHT";
	if (layoutId == AV_CH_WIDE_LEFT) return "WIDE_LEFT";
	if (layoutId == AV_CH_WIDE_RIGHT) return "WIDE_RIGHT";
	if (layoutId == AV_CH_SURROUND_DIRECT_LEFT) return "SURROUND_DIRECT_LEFT";
	if (layoutId == AV_CH_SURROUND_DIRECT_RIGHT) return "SURROUND_DIRECT_RIGHT";
	if (layoutId == AV_CH_LOW_FREQUENCY_2) return "LOW_FREQUENCY_2";
	if (layoutId == AV_CH_LAYOUT_NATIVE) return "LAYOUT_NATIVE";
	if (layoutId == AV_CH_LAYOUT_MONO) return "LAYOUT_MONO";
	if (layoutId == AV_CH_LAYOUT_STEREO) return "LAYOUT_STEREO";
	if (layoutId == AV_CH_LAYOUT_2POINT1) return "LAYOUT_2POINT1";
	if (layoutId == AV_CH_LAYOUT_2_1) return "LAYOUT_2_1";
	if (layoutId == AV_CH_LAYOUT_SURROUND) return "LAYOUT_SURROUND";
	if (layoutId == AV_CH_LAYOUT_3POINT1) return "LAYOUT_3POINT1";
	if (layoutId == AV_CH_LAYOUT_4POINT0) return "LAYOUT_4POINT0";
	if (layoutId == AV_CH_LAYOUT_4POINT1) return "LAYOUT_4POINT1";
	if (layoutId == AV_CH_LAYOUT_2_2) return "LAYOUT_2_2";
	if (layoutId == AV_CH_LAYOUT_QUAD) return "LAYOUT_QUAD";
	if (layoutId == AV_CH_LAYOUT_5POINT0) return "LAYOUT_5POINT0";
	if (layoutId == AV_CH_LAYOUT_5POINT1) return "LAYOUT_5POINT1";
	if (layoutId == AV_CH_LAYOUT_5POINT0_BACK) return "LAYOUT_5POINT0_BACK";
	if (layoutId == AV_CH_LAYOUT_5POINT1_BACK) return "LAYOUT_5POINT1_BACK";
	if (layoutId == AV_CH_LAYOUT_6POINT0) return "LAYOUT_6POINT0";
	if (layoutId == AV_CH_LAYOUT_6POINT0_FRONT) return "LAYOUT_6POINT0_FRONT";
	if (layoutId == AV_CH_LAYOUT_HEXAGONAL) return "LAYOUT_HEXAGONAL";
	if (layoutId == AV_CH_LAYOUT_6POINT1) return "LAYOUT_6POINT1";
	if (layoutId == AV_CH_LAYOUT_6POINT1_BACK) return "LAYOUT_6POINT1_BACK";
	if (layoutId == AV_CH_LAYOUT_6POINT1_FRONT) return "LAYOUT_6POINT1_FRONT";
	if (layoutId == AV_CH_LAYOUT_7POINT0) return "LAYOUT_7POINT0";
	if (layoutId == AV_CH_LAYOUT_7POINT0_FRONT) return "LAYOUT_7POINT0_FRONT";
	if (layoutId == AV_CH_LAYOUT_7POINT1) return "LAYOUT_7POINT1";
	if (layoutId == AV_CH_LAYOUT_7POINT1_WIDE) return "LAYOUT_7POINT1_WIDE";
	if (layoutId == AV_CH_LAYOUT_7POINT1_WIDE_BACK) return "LAYOUT_7POINT1_WIDE_BACK";
	if (layoutId == AV_CH_LAYOUT_OCTAGONAL) return "LAYOUT_OCTAGONAL";
	if (layoutId == AV_CH_LAYOUT_HEXADECAGONAL) return "LAYOUT_HEXADECAGONAL";
	if (layoutId == AV_CH_LAYOUT_STEREO_DOWNMIX) return "LAYOUT_STEREO_DOWNMIX";

	return "UNKNOW";
}

AVPixelFormat pixelFormatFromString(std::string formatString)
{
	if (formatString == "YUV420P") return AV_PIX_FMT_YUV420P;
	if (formatString == "NONE") return AV_PIX_FMT_NONE;
	if (formatString == "YUYV422") return AV_PIX_FMT_YUYV422;
	if (formatString == "RGB24") return AV_PIX_FMT_RGB24;
	if (formatString == "BGR24") return AV_PIX_FMT_BGR24;
	if (formatString == "YUV422P") return AV_PIX_FMT_YUV422P;
	if (formatString == "YUV444P") return AV_PIX_FMT_YUV444P;
	if (formatString == "YUV410P") return AV_PIX_FMT_YUV410P;
	if (formatString == "YUV411P") return AV_PIX_FMT_YUV411P;
	if (formatString == "GRAY8") return AV_PIX_FMT_GRAY8;
	if (formatString == "MONOWHITE") return AV_PIX_FMT_MONOWHITE;
	if (formatString == "MONOBLACK") return AV_PIX_FMT_MONOBLACK;
	if (formatString == "PAL8") return AV_PIX_FMT_PAL8;
	if (formatString == "YUVJ420P") return AV_PIX_FMT_YUVJ420P;
	if (formatString == "YUVJ422P") return AV_PIX_FMT_YUVJ422P;
	if (formatString == "YUVJ444P") return AV_PIX_FMT_YUVJ444P;
	if (formatString == "UYVY422") return AV_PIX_FMT_UYVY422;
	if (formatString == "UYYVYY411") return AV_PIX_FMT_UYYVYY411;
	if (formatString == "BGR8") return AV_PIX_FMT_BGR8;
	if (formatString == "BGR4") return AV_PIX_FMT_BGR4;
	if (formatString == "BGR4_BYTE") return AV_PIX_FMT_BGR4_BYTE;
	if (formatString == "RGB8") return AV_PIX_FMT_RGB8;
	if (formatString == "RGB4") return AV_PIX_FMT_RGB4;
	if (formatString == "RGB4_BYTE") return AV_PIX_FMT_RGB4_BYTE;
	if (formatString == "NV12") return AV_PIX_FMT_NV12;
	if (formatString == "NV21") return AV_PIX_FMT_NV21;
	if (formatString == "ARGB") return AV_PIX_FMT_ARGB;
	if (formatString == "RGBA") return AV_PIX_FMT_RGBA;
	if (formatString == "ABGR") return AV_PIX_FMT_ABGR;
	if (formatString == "BGRA") return AV_PIX_FMT_BGRA;
	if (formatString == "GRAY16BE") return AV_PIX_FMT_GRAY16BE;
	if (formatString == "GRAY16LE") return AV_PIX_FMT_GRAY16LE;
	if (formatString == "YUV440P") return AV_PIX_FMT_YUV440P;
	if (formatString == "YUVJ440P") return AV_PIX_FMT_YUVJ440P;
	if (formatString == "YUVA420P") return AV_PIX_FMT_YUVA420P;
	if (formatString == "RGB48BE") return AV_PIX_FMT_RGB48BE;
	if (formatString == "RGB48LE") return AV_PIX_FMT_RGB48LE;
	if (formatString == "RGB565BE") return AV_PIX_FMT_RGB565BE;
	if (formatString == "RGB565LE") return AV_PIX_FMT_RGB565LE;
	if (formatString == "RGB555BE") return AV_PIX_FMT_RGB555BE;
	if (formatString == "RGB555LE") return AV_PIX_FMT_RGB555LE;
	if (formatString == "BGR565BE") return AV_PIX_FMT_BGR565BE;
	if (formatString == "BGR565LE") return AV_PIX_FMT_BGR565LE;
	if (formatString == "BGR555BE") return AV_PIX_FMT_BGR555BE;
	if (formatString == "BGR555LE") return AV_PIX_FMT_BGR555LE;
	if (formatString == "VAAPI_MOCO") return AV_PIX_FMT_VAAPI_MOCO;
	if (formatString == "VAAPI_IDCT") return AV_PIX_FMT_VAAPI_IDCT;
	if (formatString == "VAAPI_VLD") return AV_PIX_FMT_VAAPI_VLD;
	if (formatString == "YUV420P16LE") return AV_PIX_FMT_YUV420P16LE;
	if (formatString == "YUV420P16BE") return AV_PIX_FMT_YUV420P16BE;
	if (formatString == "YUV422P16LE") return AV_PIX_FMT_YUV422P16LE;
	if (formatString == "YUV422P16BE") return AV_PIX_FMT_YUV422P16BE;
	if (formatString == "YUV444P16LE") return AV_PIX_FMT_YUV444P16LE;
	if (formatString == "YUV444P16BE") return AV_PIX_FMT_YUV444P16BE;
	if (formatString == "DXVA2_VLD") return AV_PIX_FMT_DXVA2_VLD;
	if (formatString == "RGB444LE") return AV_PIX_FMT_RGB444LE;
	if (formatString == "RGB444BE") return AV_PIX_FMT_RGB444BE;
	if (formatString == "BGR444LE") return AV_PIX_FMT_BGR444LE;
	if (formatString == "BGR444BE") return AV_PIX_FMT_BGR444BE;
	if (formatString == "YA8") return AV_PIX_FMT_YA8;
	if (formatString == "BGR48BE") return AV_PIX_FMT_BGR48BE;
	if (formatString == "BGR48LE") return AV_PIX_FMT_BGR48LE;
	if (formatString == "YUV420P9BE") return AV_PIX_FMT_YUV420P9BE;
	if (formatString == "YUV420P9LE") return AV_PIX_FMT_YUV420P9LE;
	if (formatString == "YUV420P10BE") return AV_PIX_FMT_YUV420P10BE;
	if (formatString == "YUV420P10LE") return AV_PIX_FMT_YUV420P10LE;
	if (formatString == "YUV422P10BE") return AV_PIX_FMT_YUV422P10BE;
	if (formatString == "YUV422P10LE") return AV_PIX_FMT_YUV422P10LE;
	if (formatString == "YUV444P9BE") return AV_PIX_FMT_YUV444P9BE;
	if (formatString == "YUV444P9LE") return AV_PIX_FMT_YUV444P9LE;
	if (formatString == "YUV444P10BE") return AV_PIX_FMT_YUV444P10BE;
	if (formatString == "YUV444P10LE") return AV_PIX_FMT_YUV444P10LE;
	if (formatString == "YUV422P9BE") return AV_PIX_FMT_YUV422P9BE;
	if (formatString == "YUV422P9LE") return AV_PIX_FMT_YUV422P9LE;
	if (formatString == "GBRP") return AV_PIX_FMT_GBRP;
	if (formatString == "GBRP9BE") return AV_PIX_FMT_GBRP9BE;
	if (formatString == "GBRP9LE") return AV_PIX_FMT_GBRP9LE;
	if (formatString == "GBRP10BE") return AV_PIX_FMT_GBRP10BE;
	if (formatString == "GBRP10LE") return AV_PIX_FMT_GBRP10LE;
	if (formatString == "GBRP16BE") return AV_PIX_FMT_GBRP16BE;
	if (formatString == "GBRP16LE") return AV_PIX_FMT_GBRP16LE;
	if (formatString == "YUVA422P") return AV_PIX_FMT_YUVA422P;
	if (formatString == "YUVA444P") return AV_PIX_FMT_YUVA444P;
	if (formatString == "YUVA420P9BE") return AV_PIX_FMT_YUVA420P9BE;
	if (formatString == "YUVA420P9LE") return AV_PIX_FMT_YUVA420P9LE;
	if (formatString == "YUVA422P9BE") return AV_PIX_FMT_YUVA422P9BE;
	if (formatString == "YUVA422P9LE") return AV_PIX_FMT_YUVA422P9LE;
	if (formatString == "YUVA444P9BE") return AV_PIX_FMT_YUVA444P9BE;
	if (formatString == "YUVA444P9LE") return AV_PIX_FMT_YUVA444P9LE;
	if (formatString == "YUVA420P10BE") return AV_PIX_FMT_YUVA420P10BE;
	if (formatString == "YUVA420P10LE") return AV_PIX_FMT_YUVA420P10LE;
	if (formatString == "YUVA422P10BE") return AV_PIX_FMT_YUVA422P10BE;
	if (formatString == "YUVA422P10LE") return AV_PIX_FMT_YUVA422P10LE;
	if (formatString == "YUVA444P10BE") return AV_PIX_FMT_YUVA444P10BE;
	if (formatString == "YUVA444P10LE") return AV_PIX_FMT_YUVA444P10LE;
	if (formatString == "YUVA420P16BE") return AV_PIX_FMT_YUVA420P16BE;
	if (formatString == "YUVA420P16LE") return AV_PIX_FMT_YUVA420P16LE;
	if (formatString == "YUVA422P16BE") return AV_PIX_FMT_YUVA422P16BE;
	if (formatString == "YUVA422P16LE") return AV_PIX_FMT_YUVA422P16LE;
	if (formatString == "YUVA444P16BE") return AV_PIX_FMT_YUVA444P16BE;
	if (formatString == "YUVA444P16LE") return AV_PIX_FMT_YUVA444P16LE;
	if (formatString == "VDPAU") return AV_PIX_FMT_VDPAU;
	if (formatString == "XYZ12LE") return AV_PIX_FMT_XYZ12LE;
	if (formatString == "XYZ12BE") return AV_PIX_FMT_XYZ12BE;
	if (formatString == "NV16") return AV_PIX_FMT_NV16;
	if (formatString == "NV20LE") return AV_PIX_FMT_NV20LE;
	if (formatString == "NV20BE") return AV_PIX_FMT_NV20BE;
	if (formatString == "RGBA64BE") return AV_PIX_FMT_RGBA64BE;
	if (formatString == "RGBA64LE") return AV_PIX_FMT_RGBA64LE;
	if (formatString == "BGRA64BE") return AV_PIX_FMT_BGRA64BE;
	if (formatString == "BGRA64LE") return AV_PIX_FMT_BGRA64LE;
	if (formatString == "YVYU422") return AV_PIX_FMT_YVYU422;
	if (formatString == "YA16BE") return AV_PIX_FMT_YA16BE;
	if (formatString == "YA16LE") return AV_PIX_FMT_YA16LE;
	if (formatString == "GBRAP") return AV_PIX_FMT_GBRAP;
	if (formatString == "GBRAP16BE") return AV_PIX_FMT_GBRAP16BE;
	if (formatString == "GBRAP16LE") return AV_PIX_FMT_GBRAP16LE;
	if (formatString == "QSV") return AV_PIX_FMT_QSV;
	if (formatString == "MMAL") return AV_PIX_FMT_MMAL;
	if (formatString == "D3D11VA_VLD") return AV_PIX_FMT_D3D11VA_VLD;
	if (formatString == "0RGB") return AV_PIX_FMT_0RGB;
	if (formatString == "RGB0") return AV_PIX_FMT_RGB0;
	if (formatString == "0BGR") return AV_PIX_FMT_0BGR;
	if (formatString == "BGR0") return AV_PIX_FMT_BGR0;
	if (formatString == "YUV420P12BE") return AV_PIX_FMT_YUV420P12BE;
	if (formatString == "YUV420P12LE") return AV_PIX_FMT_YUV420P12LE;
	if (formatString == "YUV420P14BE") return AV_PIX_FMT_YUV420P14BE;
	if (formatString == "YUV420P14LE") return AV_PIX_FMT_YUV420P14LE;
	if (formatString == "YUV422P12BE") return AV_PIX_FMT_YUV422P12BE;
	if (formatString == "YUV422P12LE") return AV_PIX_FMT_YUV422P12LE;
	if (formatString == "YUV422P14BE") return AV_PIX_FMT_YUV422P14BE;
	if (formatString == "YUV422P14LE") return AV_PIX_FMT_YUV422P14LE;
	if (formatString == "YUV444P12BE") return AV_PIX_FMT_YUV444P12BE;
	if (formatString == "YUV444P12LE") return AV_PIX_FMT_YUV444P12LE;
	if (formatString == "YUV444P14BE") return AV_PIX_FMT_YUV444P14BE;
	if (formatString == "YUV444P14LE") return AV_PIX_FMT_YUV444P14LE;
	if (formatString == "GBRP12BE") return AV_PIX_FMT_GBRP12BE;
	if (formatString == "GBRP12LE") return AV_PIX_FMT_GBRP12LE;
	if (formatString == "GBRP14BE") return AV_PIX_FMT_GBRP14BE;
	if (formatString == "GBRP14LE") return AV_PIX_FMT_GBRP14LE;
	if (formatString == "YUVJ411P") return AV_PIX_FMT_YUVJ411P;
	if (formatString == "BAYER_BGGR8") return AV_PIX_FMT_BAYER_BGGR8;
	if (formatString == "BAYER_RGGB8") return AV_PIX_FMT_BAYER_RGGB8;
	if (formatString == "BAYER_GBRG8") return AV_PIX_FMT_BAYER_GBRG8;
	if (formatString == "BAYER_GRBG8") return AV_PIX_FMT_BAYER_GRBG8;
	if (formatString == "BAYER_BGGR16LE") return AV_PIX_FMT_BAYER_BGGR16LE;
	if (formatString == "BAYER_BGGR16BE") return AV_PIX_FMT_BAYER_BGGR16BE;
	if (formatString == "BAYER_RGGB16LE") return AV_PIX_FMT_BAYER_RGGB16LE;
	if (formatString == "BAYER_RGGB16BE") return AV_PIX_FMT_BAYER_RGGB16BE;
	if (formatString == "BAYER_GBRG16LE") return AV_PIX_FMT_BAYER_GBRG16LE;
	if (formatString == "BAYER_GBRG16BE") return AV_PIX_FMT_BAYER_GBRG16BE;
	if (formatString == "BAYER_GRBG16LE") return AV_PIX_FMT_BAYER_GRBG16LE;
	if (formatString == "BAYER_GRBG16BE") return AV_PIX_FMT_BAYER_GRBG16BE;
	if (formatString == "YUV440P10LE") return AV_PIX_FMT_YUV440P10LE;
	if (formatString == "YUV440P10BE") return AV_PIX_FMT_YUV440P10BE;
	if (formatString == "YUV440P12LE") return AV_PIX_FMT_YUV440P12LE;
	if (formatString == "YUV440P12BE") return AV_PIX_FMT_YUV440P12BE;
	if (formatString == "AYUV64LE") return AV_PIX_FMT_AYUV64LE;
	if (formatString == "AYUV64BE") return AV_PIX_FMT_AYUV64BE;
	if (formatString == "VIDEOTOOLBOX") return AV_PIX_FMT_VIDEOTOOLBOX;
	if (formatString == "P010LE") return AV_PIX_FMT_P010LE;
	if (formatString == "P010BE") return AV_PIX_FMT_P010BE;
	if (formatString == "NB") return AV_PIX_FMT_NB;
	return AV_PIX_FMT_NONE;
}

std::string getPixelFormatId(int formatId)
{
	switch(formatId)
	{
		case AV_PIX_FMT_YUV420P: return "YUV420P";
		case AV_PIX_FMT_NONE: return "NONE";
		case AV_PIX_FMT_YUYV422: return "YUYV422";
		case AV_PIX_FMT_RGB24: return "RGB24";
		case AV_PIX_FMT_BGR24: return "BGR24";
		case AV_PIX_FMT_YUV422P: return "YUV422P";
		case AV_PIX_FMT_YUV444P: return "YUV444P";
		case AV_PIX_FMT_YUV410P: return "YUV410P";
		case AV_PIX_FMT_YUV411P: return "YUV411P";
		case AV_PIX_FMT_GRAY8: return "GRAY8";
		case AV_PIX_FMT_MONOWHITE: return "MONOWHITE";
		case AV_PIX_FMT_MONOBLACK: return "MONOBLACK";
		case AV_PIX_FMT_PAL8: return "PAL8";
		case AV_PIX_FMT_YUVJ420P: return "YUVJ420P";
		case AV_PIX_FMT_YUVJ422P: return "YUVJ422P";
		case AV_PIX_FMT_YUVJ444P: return "YUVJ444P";
		case AV_PIX_FMT_UYVY422: return "UYVY422";
		case AV_PIX_FMT_UYYVYY411: return "UYYVYY411";
		case AV_PIX_FMT_BGR8: return "BGR8";
		case AV_PIX_FMT_BGR4: return "BGR4";
		case AV_PIX_FMT_BGR4_BYTE: return "BGR4_BYTE";
		case AV_PIX_FMT_RGB8: return "RGB8";
		case AV_PIX_FMT_RGB4: return "RGB4";
		case AV_PIX_FMT_RGB4_BYTE: return "RGB4_BYTE";
		case AV_PIX_FMT_NV12: return "NV12";
		case AV_PIX_FMT_NV21: return "NV21";
		case AV_PIX_FMT_ARGB: return "ARGB";
		case AV_PIX_FMT_RGBA: return "RGBA";
		case AV_PIX_FMT_ABGR: return "ABGR";
		case AV_PIX_FMT_BGRA: return "BGRA";
		case AV_PIX_FMT_GRAY16BE: return "GRAY16BE";
		case AV_PIX_FMT_GRAY16LE: return "GRAY16LE";
		case AV_PIX_FMT_YUV440P: return "YUV440P";
		case AV_PIX_FMT_YUVJ440P: return "YUVJ440P";
		case AV_PIX_FMT_YUVA420P: return "YUVA420P";
		case AV_PIX_FMT_RGB48BE: return "RGB48BE";
		case AV_PIX_FMT_RGB48LE: return "RGB48LE";
		case AV_PIX_FMT_RGB565BE: return "RGB565BE";
		case AV_PIX_FMT_RGB565LE: return "RGB565LE";
		case AV_PIX_FMT_RGB555BE: return "RGB555BE";
		case AV_PIX_FMT_RGB555LE: return "RGB555LE";
		case AV_PIX_FMT_BGR565BE: return "BGR565BE";
		case AV_PIX_FMT_BGR565LE: return "BGR565LE";
		case AV_PIX_FMT_BGR555BE: return "BGR555BE";
		case AV_PIX_FMT_BGR555LE: return "BGR555LE";
		case AV_PIX_FMT_VAAPI_MOCO: return "VAAPI_MOCO";
		case AV_PIX_FMT_VAAPI_IDCT: return "VAAPI_IDCT";
		case AV_PIX_FMT_VAAPI_VLD: return "VAAPI_VLD";
		case AV_PIX_FMT_YUV420P16LE: return "YUV420P16LE";
		case AV_PIX_FMT_YUV420P16BE: return "YUV420P16BE";
		case AV_PIX_FMT_YUV422P16LE: return "YUV422P16LE";
		case AV_PIX_FMT_YUV422P16BE: return "YUV422P16BE";
		case AV_PIX_FMT_YUV444P16LE: return "YUV444P16LE";
		case AV_PIX_FMT_YUV444P16BE: return "YUV444P16BE";
		case AV_PIX_FMT_DXVA2_VLD: return "DXVA2_VLD";
		case AV_PIX_FMT_RGB444LE: return "RGB444LE";
		case AV_PIX_FMT_RGB444BE: return "RGB444BE";
		case AV_PIX_FMT_BGR444LE: return "BGR444LE";
		case AV_PIX_FMT_BGR444BE: return "BGR444BE";
		case AV_PIX_FMT_YA8: return "YA8";
		case AV_PIX_FMT_BGR48BE: return "BGR48BE";
		case AV_PIX_FMT_BGR48LE: return "BGR48LE";
		case AV_PIX_FMT_YUV420P9BE: return "YUV420P9BE";
		case AV_PIX_FMT_YUV420P9LE: return "YUV420P9LE";
		case AV_PIX_FMT_YUV420P10BE: return "YUV420P10BE";
		case AV_PIX_FMT_YUV420P10LE: return "YUV420P10LE";
		case AV_PIX_FMT_YUV422P10BE: return "YUV422P10BE";
		case AV_PIX_FMT_YUV422P10LE: return "YUV422P10LE";
		case AV_PIX_FMT_YUV444P9BE: return "YUV444P9BE";
		case AV_PIX_FMT_YUV444P9LE: return "YUV444P9LE";
		case AV_PIX_FMT_YUV444P10BE: return "YUV444P10BE";
		case AV_PIX_FMT_YUV444P10LE: return "YUV444P10LE";
		case AV_PIX_FMT_YUV422P9BE: return "YUV422P9BE";
		case AV_PIX_FMT_YUV422P9LE: return "YUV422P9LE";
		case AV_PIX_FMT_GBRP: return "GBRP";
		case AV_PIX_FMT_GBRP9BE: return "GBRP9BE";
		case AV_PIX_FMT_GBRP9LE: return "GBRP9LE";
		case AV_PIX_FMT_GBRP10BE: return "GBRP10BE";
		case AV_PIX_FMT_GBRP10LE: return "GBRP10LE";
		case AV_PIX_FMT_GBRP16BE: return "GBRP16BE";
		case AV_PIX_FMT_GBRP16LE: return "GBRP16LE";
		case AV_PIX_FMT_YUVA422P: return "YUVA422P";
		case AV_PIX_FMT_YUVA444P: return "YUVA444P";
		case AV_PIX_FMT_YUVA420P9BE: return "YUVA420P9BE";
		case AV_PIX_FMT_YUVA420P9LE: return "YUVA420P9LE";
		case AV_PIX_FMT_YUVA422P9BE: return "YUVA422P9BE";
		case AV_PIX_FMT_YUVA422P9LE: return "YUVA422P9LE";
		case AV_PIX_FMT_YUVA444P9BE: return "YUVA444P9BE";
		case AV_PIX_FMT_YUVA444P9LE: return "YUVA444P9LE";
		case AV_PIX_FMT_YUVA420P10BE: return "YUVA420P10BE";
		case AV_PIX_FMT_YUVA420P10LE: return "YUVA420P10LE";
		case AV_PIX_FMT_YUVA422P10BE: return "YUVA422P10BE";
		case AV_PIX_FMT_YUVA422P10LE: return "YUVA422P10LE";
		case AV_PIX_FMT_YUVA444P10BE: return "YUVA444P10BE";
		case AV_PIX_FMT_YUVA444P10LE: return "YUVA444P10LE";
		case AV_PIX_FMT_YUVA420P16BE: return "YUVA420P16BE";
		case AV_PIX_FMT_YUVA420P16LE: return "YUVA420P16LE";
		case AV_PIX_FMT_YUVA422P16BE: return "YUVA422P16BE";
		case AV_PIX_FMT_YUVA422P16LE: return "YUVA422P16LE";
		case AV_PIX_FMT_YUVA444P16BE: return "YUVA444P16BE";
		case AV_PIX_FMT_YUVA444P16LE: return "YUVA444P16LE";
		case AV_PIX_FMT_VDPAU: return "VDPAU";
		case AV_PIX_FMT_XYZ12LE: return "XYZ12LE";
		case AV_PIX_FMT_XYZ12BE: return "XYZ12BE";
		case AV_PIX_FMT_NV16: return "NV16";
		case AV_PIX_FMT_NV20LE: return "NV20LE";
		case AV_PIX_FMT_NV20BE: return "NV20BE";
		case AV_PIX_FMT_RGBA64BE: return "RGBA64BE";
		case AV_PIX_FMT_RGBA64LE: return "RGBA64LE";
		case AV_PIX_FMT_BGRA64BE: return "BGRA64BE";
		case AV_PIX_FMT_BGRA64LE: return "BGRA64LE";
		case AV_PIX_FMT_YVYU422: return "YVYU422";
		case AV_PIX_FMT_YA16BE: return "YA16BE";
		case AV_PIX_FMT_YA16LE: return "YA16LE";
		case AV_PIX_FMT_GBRAP: return "GBRAP";
		case AV_PIX_FMT_GBRAP16BE: return "GBRAP16BE";
		case AV_PIX_FMT_GBRAP16LE: return "GBRAP16LE";
		case AV_PIX_FMT_QSV: return "QSV";
		case AV_PIX_FMT_MMAL: return "MMAL";
		case AV_PIX_FMT_D3D11VA_VLD: return "D3D11VA_VLD";
		case AV_PIX_FMT_0RGB: return "0RGB";
		case AV_PIX_FMT_RGB0: return "RGB0";
		case AV_PIX_FMT_0BGR: return "0BGR";
		case AV_PIX_FMT_BGR0: return "BGR0";
		case AV_PIX_FMT_YUV420P12BE: return "YUV420P12BE";
		case AV_PIX_FMT_YUV420P12LE: return "YUV420P12LE";
		case AV_PIX_FMT_YUV420P14BE: return "YUV420P14BE";
		case AV_PIX_FMT_YUV420P14LE: return "YUV420P14LE";
		case AV_PIX_FMT_YUV422P12BE: return "YUV422P12BE";
		case AV_PIX_FMT_YUV422P12LE: return "YUV422P12LE";
		case AV_PIX_FMT_YUV422P14BE: return "YUV422P14BE";
		case AV_PIX_FMT_YUV422P14LE: return "YUV422P14LE";
		case AV_PIX_FMT_YUV444P12BE: return "YUV444P12BE";
		case AV_PIX_FMT_YUV444P12LE: return "YUV444P12LE";
		case AV_PIX_FMT_YUV444P14BE: return "YUV444P14BE";
		case AV_PIX_FMT_YUV444P14LE: return "YUV444P14LE";
		case AV_PIX_FMT_GBRP12BE: return "GBRP12BE";
		case AV_PIX_FMT_GBRP12LE: return "GBRP12LE";
		case AV_PIX_FMT_GBRP14BE: return "GBRP14BE";
		case AV_PIX_FMT_GBRP14LE: return "GBRP14LE";
		case AV_PIX_FMT_YUVJ411P: return "YUVJ411P";
		case AV_PIX_FMT_BAYER_BGGR8: return "BAYER_BGGR8";
		case AV_PIX_FMT_BAYER_RGGB8: return "BAYER_RGGB8";
		case AV_PIX_FMT_BAYER_GBRG8: return "BAYER_GBRG8";
		case AV_PIX_FMT_BAYER_GRBG8: return "BAYER_GRBG8";
		case AV_PIX_FMT_BAYER_BGGR16LE: return "BAYER_BGGR16LE";
		case AV_PIX_FMT_BAYER_BGGR16BE: return "BAYER_BGGR16BE";
		case AV_PIX_FMT_BAYER_RGGB16LE: return "BAYER_RGGB16LE";
		case AV_PIX_FMT_BAYER_RGGB16BE: return "BAYER_RGGB16BE";
		case AV_PIX_FMT_BAYER_GBRG16LE: return "BAYER_GBRG16LE";
		case AV_PIX_FMT_BAYER_GBRG16BE: return "BAYER_GBRG16BE";
		case AV_PIX_FMT_BAYER_GRBG16LE: return "BAYER_GRBG16LE";
		case AV_PIX_FMT_BAYER_GRBG16BE: return "BAYER_GRBG16BE";
		case AV_PIX_FMT_YUV440P10LE: return "YUV440P10LE";
		case AV_PIX_FMT_YUV440P10BE: return "YUV440P10BE";
		case AV_PIX_FMT_YUV440P12LE: return "YUV440P12LE";
		case AV_PIX_FMT_YUV440P12BE: return "YUV440P12BE";
		case AV_PIX_FMT_AYUV64LE: return "AYUV64LE";
		case AV_PIX_FMT_AYUV64BE: return "AYUV64BE";
		case AV_PIX_FMT_VIDEOTOOLBOX: return "VIDEOTOOLBOX";
		case AV_PIX_FMT_P010LE: return "P010LE";
		case AV_PIX_FMT_P010BE: return "P010BE";
		case AV_PIX_FMT_NB: return "NB";
		default: return "UNKNOW";
	}
}

std::string getSampleFormatId(int formatId)
{
	switch(formatId)
	{
		case AV_SAMPLE_FMT_NONE: return "NONE";
		case AV_SAMPLE_FMT_U8: return "U8";
		case AV_SAMPLE_FMT_S16: return "S16";
		case AV_SAMPLE_FMT_S32: return "S32";
		case AV_SAMPLE_FMT_FLT: return "FLT";
		case AV_SAMPLE_FMT_DBL: return "DBL";
		case AV_SAMPLE_FMT_U8P: return "U8P";
		case AV_SAMPLE_FMT_S16P: return "S16P";
		case AV_SAMPLE_FMT_S32P: return "S32P";
		case AV_SAMPLE_FMT_FLTP: return "FLTP";
		case AV_SAMPLE_FMT_DBLP: return "DBLP";
		case AV_SAMPLE_FMT_NB: return "NB";
		default: return "UNKNOW";
	}
}

std::string getCodecId(int codecId)
{
    switch(codecId)
    {
        case AV_CODEC_ID_NONE: return "NONE";
        case AV_CODEC_ID_MPEG1VIDEO: return "MPEG1VIDEO";
        case AV_CODEC_ID_MPEG2VIDEO: return "MPEG2VIDEO";
        case AV_CODEC_ID_H261: return "H261";
        case AV_CODEC_ID_H263: return "H263";
        case AV_CODEC_ID_RV10: return "RV10";
        case AV_CODEC_ID_RV20: return "RV20";
        case AV_CODEC_ID_MJPEG: return "MJPEG";
        case AV_CODEC_ID_MJPEGB: return "MJPEGB";
        case AV_CODEC_ID_LJPEG: return "LJPEG";
        case AV_CODEC_ID_SP5X: return "SP5X";
        case AV_CODEC_ID_JPEGLS: return "JPEGLS";
        case AV_CODEC_ID_MPEG4: return "MPEG4";
        case AV_CODEC_ID_RAWVIDEO: return "RAWVIDEO";
        case AV_CODEC_ID_MSMPEG4V1: return "MSMPEG4V1";
        case AV_CODEC_ID_MSMPEG4V2: return "MSMPEG4V2";
        case AV_CODEC_ID_MSMPEG4V3: return "MSMPEG4V3";
        case AV_CODEC_ID_WMV1: return "WMV1";
        case AV_CODEC_ID_WMV2: return "WMV2";
        case AV_CODEC_ID_H263P: return "H263P";
        case AV_CODEC_ID_H263I: return "H263I";
        case AV_CODEC_ID_FLV1: return "FLV1";
        case AV_CODEC_ID_SVQ1: return "SVQ1";
        case AV_CODEC_ID_SVQ3: return "SVQ3";
        case AV_CODEC_ID_DVVIDEO: return "DVVIDEO";
        case AV_CODEC_ID_HUFFYUV: return "HUFFYUV";
        case AV_CODEC_ID_CYUV: return "CYUV";
        case AV_CODEC_ID_H264: return "H264";
        case AV_CODEC_ID_INDEO3: return "INDEO3";
        case AV_CODEC_ID_VP3: return "VP3";
        case AV_CODEC_ID_THEORA: return "THEORA";
        case AV_CODEC_ID_ASV1: return "ASV1";
        case AV_CODEC_ID_ASV2: return "ASV2";
        case AV_CODEC_ID_FFV1: return "FFV1";
        case AV_CODEC_ID_4XM: return "4XM";
        case AV_CODEC_ID_VCR1: return "VCR1";
        case AV_CODEC_ID_CLJR: return "CLJR";
        case AV_CODEC_ID_MDEC: return "MDEC";
        case AV_CODEC_ID_ROQ: return "ROQ";
        case AV_CODEC_ID_INTERPLAY_VIDEO: return "INTERPLAY_VIDEO";
        case AV_CODEC_ID_XAN_WC3: return "XAN_WC3";
        case AV_CODEC_ID_XAN_WC4: return "XAN_WC4";
        case AV_CODEC_ID_RPZA: return "RPZA";
        case AV_CODEC_ID_CINEPAK: return "CINEPAK";
        case AV_CODEC_ID_WS_VQA: return "WS_VQA";
        case AV_CODEC_ID_MSRLE: return "MSRLE";
        case AV_CODEC_ID_MSVIDEO1: return "MSVIDEO1";
        case AV_CODEC_ID_IDCIN: return "IDCIN";
        case AV_CODEC_ID_8BPS: return "8BPS";
        case AV_CODEC_ID_SMC: return "SMC";
        case AV_CODEC_ID_FLIC: return "FLIC";
        case AV_CODEC_ID_TRUEMOTION1: return "TRUEMOTION1";
        case AV_CODEC_ID_VMDVIDEO: return "VMDVIDEO";
        case AV_CODEC_ID_MSZH: return "MSZH";
        case AV_CODEC_ID_ZLIB: return "ZLIB";
        case AV_CODEC_ID_QTRLE: return "QTRLE";
        case AV_CODEC_ID_TSCC: return "TSCC";
        case AV_CODEC_ID_ULTI: return "ULTI";
        case AV_CODEC_ID_QDRAW: return "QDRAW";
        case AV_CODEC_ID_VIXL: return "VIXL";
        case AV_CODEC_ID_QPEG: return "QPEG";
        case AV_CODEC_ID_PNG: return "PNG";
        case AV_CODEC_ID_PPM: return "PPM";
        case AV_CODEC_ID_PBM: return "PBM";
        case AV_CODEC_ID_PGM: return "PGM";
        case AV_CODEC_ID_PGMYUV: return "PGMYUV";
        case AV_CODEC_ID_PAM: return "PAM";
        case AV_CODEC_ID_FFVHUFF: return "FFVHUFF";
        case AV_CODEC_ID_RV30: return "RV30";
        case AV_CODEC_ID_RV40: return "RV40";
        case AV_CODEC_ID_VC1: return "VC1";
        case AV_CODEC_ID_WMV3: return "WMV3";
        case AV_CODEC_ID_LOCO: return "LOCO";
        case AV_CODEC_ID_WNV1: return "WNV1";
        case AV_CODEC_ID_AASC: return "AASC";
        case AV_CODEC_ID_INDEO2: return "INDEO2";
        case AV_CODEC_ID_FRAPS: return "FRAPS";
        case AV_CODEC_ID_TRUEMOTION2: return "TRUEMOTION2";
        case AV_CODEC_ID_BMP: return "BMP";
        case AV_CODEC_ID_CSCD: return "CSCD";
        case AV_CODEC_ID_MMVIDEO: return "MMVIDEO";
        case AV_CODEC_ID_ZMBV: return "ZMBV";
        case AV_CODEC_ID_AVS: return "AVS";
        case AV_CODEC_ID_SMACKVIDEO: return "SMACKVIDEO";
        case AV_CODEC_ID_NUV: return "NUV";
        case AV_CODEC_ID_KMVC: return "KMVC";
        case AV_CODEC_ID_FLASHSV: return "FLASHSV";
        case AV_CODEC_ID_CAVS: return "CAVS";
        case AV_CODEC_ID_JPEG2000: return "JPEG2000";
        case AV_CODEC_ID_VMNC: return "VMNC";
        case AV_CODEC_ID_VP5: return "VP5";
        case AV_CODEC_ID_VP6: return "VP6";
        case AV_CODEC_ID_VP6F: return "VP6F";
        case AV_CODEC_ID_TARGA: return "TARGA";
        case AV_CODEC_ID_DSICINVIDEO: return "DSICINVIDEO";
        case AV_CODEC_ID_TIERTEXSEQVIDEO: return "TIERTEXSEQVIDEO";
        case AV_CODEC_ID_TIFF: return "TIFF";
        case AV_CODEC_ID_GIF: return "GIF";
        case AV_CODEC_ID_DXA: return "DXA";
        case AV_CODEC_ID_DNXHD: return "DNXHD";
        case AV_CODEC_ID_THP: return "THP";
        case AV_CODEC_ID_SGI: return "SGI";
        case AV_CODEC_ID_C93: return "C93";
        case AV_CODEC_ID_BETHSOFTVID: return "BETHSOFTVID";
        case AV_CODEC_ID_PTX: return "PTX";
        case AV_CODEC_ID_TXD: return "TXD";
        case AV_CODEC_ID_VP6A: return "VP6A";
        case AV_CODEC_ID_AMV: return "AMV";
        case AV_CODEC_ID_VB: return "VB";
        case AV_CODEC_ID_PCX: return "PCX";
        case AV_CODEC_ID_SUNRAST: return "SUNRAST";
        case AV_CODEC_ID_INDEO4: return "INDEO4";
        case AV_CODEC_ID_INDEO5: return "INDEO5";
        case AV_CODEC_ID_MIMIC: return "MIMIC";
        case AV_CODEC_ID_RL2: return "RL2";
        case AV_CODEC_ID_ESCAPE124: return "ESCAPE124";
        case AV_CODEC_ID_DIRAC: return "DIRAC";
        case AV_CODEC_ID_BFI: return "BFI";
        case AV_CODEC_ID_CMV: return "CMV";
        case AV_CODEC_ID_MOTIONPIXELS: return "MOTIONPIXELS";
        case AV_CODEC_ID_TGV: return "TGV";
        case AV_CODEC_ID_TGQ: return "TGQ";
        case AV_CODEC_ID_TQI: return "TQI";
        case AV_CODEC_ID_AURA: return "AURA";
        case AV_CODEC_ID_AURA2: return "AURA2";
        case AV_CODEC_ID_V210X: return "V210X";
        case AV_CODEC_ID_TMV: return "TMV";
        case AV_CODEC_ID_V210: return "V210";
        case AV_CODEC_ID_DPX: return "DPX";
        case AV_CODEC_ID_MAD: return "MAD";
        case AV_CODEC_ID_FRWU: return "FRWU";
        case AV_CODEC_ID_FLASHSV2: return "FLASHSV2";
        case AV_CODEC_ID_CDGRAPHICS: return "CDGRAPHICS";
        case AV_CODEC_ID_R210: return "R210";
        case AV_CODEC_ID_ANM: return "ANM";
        case AV_CODEC_ID_BINKVIDEO: return "BINKVIDEO";
        case AV_CODEC_ID_IFF_ILBM: return "IFF_ILBM";
        case AV_CODEC_ID_KGV1: return "KGV1";
        case AV_CODEC_ID_YOP: return "YOP";
        case AV_CODEC_ID_VP8: return "VP8";
        case AV_CODEC_ID_PICTOR: return "PICTOR";
        case AV_CODEC_ID_ANSI: return "ANSI";
        case AV_CODEC_ID_A64_MULTI: return "A64_MULTI";
        case AV_CODEC_ID_A64_MULTI5: return "A64_MULTI5";
        case AV_CODEC_ID_R10K: return "R10K";
        case AV_CODEC_ID_MXPEG: return "MXPEG";
        case AV_CODEC_ID_LAGARITH: return "LAGARITH";
        case AV_CODEC_ID_PRORES: return "PRORES";
        case AV_CODEC_ID_JV: return "JV";
        case AV_CODEC_ID_DFA: return "DFA";
        case AV_CODEC_ID_WMV3IMAGE: return "WMV3IMAGE";
        case AV_CODEC_ID_VC1IMAGE: return "VC1IMAGE";
        case AV_CODEC_ID_UTVIDEO: return "UTVIDEO";
        case AV_CODEC_ID_BMV_VIDEO: return "BMV_VIDEO";
        case AV_CODEC_ID_VBLE: return "VBLE";
        case AV_CODEC_ID_DXTORY: return "DXTORY";
        case AV_CODEC_ID_V410: return "V410";
        case AV_CODEC_ID_XWD: return "XWD";
        case AV_CODEC_ID_CDXL: return "CDXL";
        case AV_CODEC_ID_XBM: return "XBM";
        case AV_CODEC_ID_ZEROCODEC: return "ZEROCODEC";
        case AV_CODEC_ID_MSS1: return "MSS1";
        case AV_CODEC_ID_MSA1: return "MSA1";
        case AV_CODEC_ID_TSCC2: return "TSCC2";
        case AV_CODEC_ID_MTS2: return "MTS2";
        case AV_CODEC_ID_CLLC: return "CLLC";
        case AV_CODEC_ID_MSS2: return "MSS2";
        case AV_CODEC_ID_VP9: return "VP9";
        case AV_CODEC_ID_AIC: return "AIC";
        case AV_CODEC_ID_ESCAPE130: return "ESCAPE130";
        case AV_CODEC_ID_G2M: return "G2M";
        case AV_CODEC_ID_WEBP: return "WEBP";
        case AV_CODEC_ID_HNM4_VIDEO: return "HNM4_VIDEO";
        case AV_CODEC_ID_HEVC: return "HEVC";
        case AV_CODEC_ID_FIC: return "FIC";
        case AV_CODEC_ID_ALIAS_PIX: return "ALIAS_PIX";
        case AV_CODEC_ID_BRENDER_PIX: return "BRENDER_PIX";
        case AV_CODEC_ID_PAF_VIDEO: return "PAF_VIDEO";
        case AV_CODEC_ID_EXR: return "EXR";
        case AV_CODEC_ID_VP7: return "VP7";
        case AV_CODEC_ID_SANM: return "SANM";
        case AV_CODEC_ID_SGIRLE: return "SGIRLE";
        case AV_CODEC_ID_MVC1: return "MVC1";
        case AV_CODEC_ID_MVC2: return "MVC2";
        case AV_CODEC_ID_HQX: return "HQX";
        case AV_CODEC_ID_TDSC: return "TDSC";
        case AV_CODEC_ID_HQ_HQA: return "HQ_HQA";
        case AV_CODEC_ID_HAP: return "HAP";
        case AV_CODEC_ID_DDS: return "DDS";
        case AV_CODEC_ID_DXV: return "DXV";
        case AV_CODEC_ID_SCREENPRESSO: return "SCREENPRESSO";
        case AV_CODEC_ID_RSCC: return "RSCC";
        case AV_CODEC_ID_Y41P: return "Y41P";
        case AV_CODEC_ID_AVRP: return "AVRP";
        case AV_CODEC_ID_012V: return "012V";
        case AV_CODEC_ID_AVUI: return "AVUI";
        case AV_CODEC_ID_AYUV: return "AYUV";
        case AV_CODEC_ID_TARGA_Y216: return "TARGA_Y216";
        case AV_CODEC_ID_V308: return "V308";
        case AV_CODEC_ID_V408: return "V408";
        case AV_CODEC_ID_YUV4: return "YUV4";
        case AV_CODEC_ID_AVRN: return "AVRN";
        case AV_CODEC_ID_CPIA: return "CPIA";
        case AV_CODEC_ID_XFACE: return "XFACE";
        case AV_CODEC_ID_SNOW: return "SNOW";
        case AV_CODEC_ID_SMVJPEG: return "SMVJPEG";
        case AV_CODEC_ID_APNG: return "APNG";
        case AV_CODEC_ID_DAALA: return "DAALA";
        case AV_CODEC_ID_CFHD: return "CFHD";
        case AV_CODEC_ID_FIRST_AUDIO: return "FIRST_AUDIO";
        case AV_CODEC_ID_PCM_S16BE: return "PCM_S16BE";
        case AV_CODEC_ID_PCM_U16LE: return "PCM_U16LE";
        case AV_CODEC_ID_PCM_U16BE: return "PCM_U16BE";
        case AV_CODEC_ID_PCM_S8: return "PCM_S8";
        case AV_CODEC_ID_PCM_U8: return "PCM_U8";
        case AV_CODEC_ID_PCM_MULAW: return "PCM_MULAW";
        case AV_CODEC_ID_PCM_ALAW: return "PCM_ALAW";
        case AV_CODEC_ID_PCM_S32LE: return "PCM_S32LE";
        case AV_CODEC_ID_PCM_S32BE: return "PCM_S32BE";
        case AV_CODEC_ID_PCM_U32LE: return "PCM_U32LE";
        case AV_CODEC_ID_PCM_U32BE: return "PCM_U32BE";
        case AV_CODEC_ID_PCM_S24LE: return "PCM_S24LE";
        case AV_CODEC_ID_PCM_S24BE: return "PCM_S24BE";
        case AV_CODEC_ID_PCM_U24LE: return "PCM_U24LE";
        case AV_CODEC_ID_PCM_U24BE: return "PCM_U24BE";
        case AV_CODEC_ID_PCM_S24DAUD: return "PCM_S24DAUD";
        case AV_CODEC_ID_PCM_ZORK: return "PCM_ZORK";
        case AV_CODEC_ID_PCM_S16LE_PLANAR: return "PCM_S16LE_PLANAR";
        case AV_CODEC_ID_PCM_DVD: return "PCM_DVD";
        case AV_CODEC_ID_PCM_F32BE: return "PCM_F32BE";
        case AV_CODEC_ID_PCM_F32LE: return "PCM_F32LE";
        case AV_CODEC_ID_PCM_F64BE: return "PCM_F64BE";
        case AV_CODEC_ID_PCM_F64LE: return "PCM_F64LE";
        case AV_CODEC_ID_PCM_BLURAY: return "PCM_BLURAY";
        case AV_CODEC_ID_PCM_LXF: return "PCM_LXF";
        case AV_CODEC_ID_S302M: return "S302M";
        case AV_CODEC_ID_PCM_S8_PLANAR: return "PCM_S8_PLANAR";
        case AV_CODEC_ID_PCM_S24LE_PLANAR: return "PCM_S24LE_PLANAR";
        case AV_CODEC_ID_PCM_S32LE_PLANAR: return "PCM_S32LE_PLANAR";
        case AV_CODEC_ID_PCM_S16BE_PLANAR: return "PCM_S16BE_PLANAR";
        case AV_CODEC_ID_ADPCM_IMA_QT: return "ADPCM_IMA_QT";
        case AV_CODEC_ID_ADPCM_IMA_WAV: return "ADPCM_IMA_WAV";
        case AV_CODEC_ID_ADPCM_IMA_DK3: return "ADPCM_IMA_DK3";
        case AV_CODEC_ID_ADPCM_IMA_DK4: return "ADPCM_IMA_DK4";
        case AV_CODEC_ID_ADPCM_IMA_WS: return "ADPCM_IMA_WS";
        case AV_CODEC_ID_ADPCM_IMA_SMJPEG: return "ADPCM_IMA_SMJPEG";
        case AV_CODEC_ID_ADPCM_MS: return "ADPCM_MS";
        case AV_CODEC_ID_ADPCM_4XM: return "ADPCM_4XM";
        case AV_CODEC_ID_ADPCM_XA: return "ADPCM_XA";
        case AV_CODEC_ID_ADPCM_ADX: return "ADPCM_ADX";
        case AV_CODEC_ID_ADPCM_EA: return "ADPCM_EA";
        case AV_CODEC_ID_ADPCM_G726: return "ADPCM_G726";
        case AV_CODEC_ID_ADPCM_CT: return "ADPCM_CT";
        case AV_CODEC_ID_ADPCM_SWF: return "ADPCM_SWF";
        case AV_CODEC_ID_ADPCM_YAMAHA: return "ADPCM_YAMAHA";
        case AV_CODEC_ID_ADPCM_SBPRO_4: return "ADPCM_SBPRO_4";
        case AV_CODEC_ID_ADPCM_SBPRO_3: return "ADPCM_SBPRO_3";
        case AV_CODEC_ID_ADPCM_SBPRO_2: return "ADPCM_SBPRO_2";
        case AV_CODEC_ID_ADPCM_THP: return "ADPCM_THP";
        case AV_CODEC_ID_ADPCM_IMA_AMV: return "ADPCM_IMA_AMV";
        case AV_CODEC_ID_ADPCM_EA_R1: return "ADPCM_EA_R1";
        case AV_CODEC_ID_ADPCM_EA_R3: return "ADPCM_EA_R3";
        case AV_CODEC_ID_ADPCM_EA_R2: return "ADPCM_EA_R2";
        case AV_CODEC_ID_ADPCM_IMA_EA_SEAD: return "ADPCM_IMA_EA_SEAD";
        case AV_CODEC_ID_ADPCM_IMA_EA_EACS: return "ADPCM_IMA_EA_EACS";
        case AV_CODEC_ID_ADPCM_EA_XAS: return "ADPCM_EA_XAS";
        case AV_CODEC_ID_ADPCM_EA_MAXIS_XA: return "ADPCM_EA_MAXIS_XA";
        case AV_CODEC_ID_ADPCM_IMA_ISS: return "ADPCM_IMA_ISS";
        case AV_CODEC_ID_ADPCM_G722: return "ADPCM_G722";
        case AV_CODEC_ID_ADPCM_IMA_APC: return "ADPCM_IMA_APC";
        case AV_CODEC_ID_ADPCM_VIMA: return "ADPCM_VIMA";
        case AV_CODEC_ID_ADPCM_AFC: return "ADPCM_AFC";
        case AV_CODEC_ID_ADPCM_IMA_OKI: return "ADPCM_IMA_OKI";
        case AV_CODEC_ID_ADPCM_DTK: return "ADPCM_DTK";
        case AV_CODEC_ID_ADPCM_IMA_RAD: return "ADPCM_IMA_RAD";
        case AV_CODEC_ID_ADPCM_G726LE: return "ADPCM_G726LE";
        case AV_CODEC_ID_ADPCM_THP_LE: return "ADPCM_THP_LE";
        case AV_CODEC_ID_ADPCM_PSX: return "ADPCM_PSX";
        case AV_CODEC_ID_ADPCM_AICA: return "ADPCM_AICA";
        case AV_CODEC_ID_AMR_NB: return "AMR_NB";
        case AV_CODEC_ID_AMR_WB: return "AMR_WB";
        case AV_CODEC_ID_RA_144: return "RA_144";
        case AV_CODEC_ID_RA_288: return "RA_288";
        case AV_CODEC_ID_ROQ_DPCM: return "ROQ_DPCM";
        case AV_CODEC_ID_INTERPLAY_DPCM: return "INTERPLAY_DPCM";
        case AV_CODEC_ID_XAN_DPCM: return "XAN_DPCM";
        case AV_CODEC_ID_SOL_DPCM: return "SOL_DPCM";
        case AV_CODEC_ID_SDX2_DPCM: return "SDX2_DPCM";
        case AV_CODEC_ID_MP2: return "MP2";
        case AV_CODEC_ID_MP3: return "MP3";
        case AV_CODEC_ID_AAC: return "AAC";
        case AV_CODEC_ID_AC3: return "AC3";
        case AV_CODEC_ID_DTS: return "DTS";
        case AV_CODEC_ID_VORBIS: return "VORBIS";
        case AV_CODEC_ID_DVAUDIO: return "DVAUDIO";
        case AV_CODEC_ID_WMAV1: return "WMAV1";
        case AV_CODEC_ID_WMAV2: return "WMAV2";
        case AV_CODEC_ID_MACE3: return "MACE3";
        case AV_CODEC_ID_MACE6: return "MACE6";
        case AV_CODEC_ID_VMDAUDIO: return "VMDAUDIO";
        case AV_CODEC_ID_FLAC: return "FLAC";
        case AV_CODEC_ID_MP3ADU: return "MP3ADU";
        case AV_CODEC_ID_MP3ON4: return "MP3ON4";
        case AV_CODEC_ID_SHORTEN: return "SHORTEN";
        case AV_CODEC_ID_ALAC: return "ALAC";
        case AV_CODEC_ID_WESTWOOD_SND1: return "WESTWOOD_SND1";
        case AV_CODEC_ID_GSM: return "GSM";
        case AV_CODEC_ID_QDM2: return "QDM2";
        case AV_CODEC_ID_COOK: return "COOK";
        case AV_CODEC_ID_TRUESPEECH: return "TRUESPEECH";
        case AV_CODEC_ID_TTA: return "TTA";
        case AV_CODEC_ID_SMACKAUDIO: return "SMACKAUDIO";
        case AV_CODEC_ID_QCELP: return "QCELP";
        case AV_CODEC_ID_WAVPACK: return "WAVPACK";
        case AV_CODEC_ID_DSICINAUDIO: return "DSICINAUDIO";
        case AV_CODEC_ID_IMC: return "IMC";
        case AV_CODEC_ID_MUSEPACK7: return "MUSEPACK7";
        case AV_CODEC_ID_MLP: return "MLP";
        case AV_CODEC_ID_GSM_MS: return "GSM_MS";
        case AV_CODEC_ID_ATRAC3: return "ATRAC3";
        case AV_CODEC_ID_NELLYMOSER: return "NELLYMOSER";
        case AV_CODEC_ID_MUSEPACK8: return "MUSEPACK8";
        case AV_CODEC_ID_SPEEX: return "SPEEX";
        case AV_CODEC_ID_WMAVOICE: return "WMAVOICE";
        case AV_CODEC_ID_WMAPRO: return "WMAPRO";
        case AV_CODEC_ID_WMALOSSLESS: return "WMALOSSLESS";
        case AV_CODEC_ID_ATRAC3P: return "ATRAC3P";
        case AV_CODEC_ID_EAC3: return "EAC3";
        case AV_CODEC_ID_SIPR: return "SIPR";
        case AV_CODEC_ID_MP1: return "MP1";
        case AV_CODEC_ID_TWINVQ: return "TWINVQ";
        case AV_CODEC_ID_TRUEHD: return "TRUEHD";
        case AV_CODEC_ID_MP4ALS: return "MP4ALS";
        case AV_CODEC_ID_ATRAC1: return "ATRAC1";
        case AV_CODEC_ID_BINKAUDIO_RDFT: return "BINKAUDIO_RDFT";
        case AV_CODEC_ID_BINKAUDIO_DCT: return "BINKAUDIO_DCT";
        case AV_CODEC_ID_AAC_LATM: return "AAC_LATM";
        case AV_CODEC_ID_QDMC: return "QDMC";
        case AV_CODEC_ID_CELT: return "CELT";
        case AV_CODEC_ID_G723_1: return "G723_1";
        case AV_CODEC_ID_G729: return "G729";
        case AV_CODEC_ID_8SVX_EXP: return "8SVX_EXP";
        case AV_CODEC_ID_8SVX_FIB: return "8SVX_FIB";
        case AV_CODEC_ID_BMV_AUDIO: return "BMV_AUDIO";
        case AV_CODEC_ID_RALF: return "RALF";
        case AV_CODEC_ID_IAC: return "IAC";
        case AV_CODEC_ID_ILBC: return "ILBC";
        case AV_CODEC_ID_OPUS: return "OPUS";
        case AV_CODEC_ID_COMFORT_NOISE: return "COMFORT_NOISE";
        case AV_CODEC_ID_TAK: return "TAK";
        case AV_CODEC_ID_METASOUND: return "METASOUND";
        case AV_CODEC_ID_PAF_AUDIO: return "PAF_AUDIO";
        case AV_CODEC_ID_ON2AVC: return "ON2AVC";
        case AV_CODEC_ID_DSS_SP: return "DSS_SP";
        case AV_CODEC_ID_FFWAVESYNTH: return "FFWAVESYNTH";
        case AV_CODEC_ID_SONIC: return "SONIC";
        case AV_CODEC_ID_SONIC_LS: return "SONIC_LS";
        case AV_CODEC_ID_EVRC: return "EVRC";
        case AV_CODEC_ID_SMV: return "SMV";
        case AV_CODEC_ID_DSD_LSBF: return "DSD_LSBF";
        case AV_CODEC_ID_DSD_MSBF: return "DSD_MSBF";
        case AV_CODEC_ID_DSD_LSBF_PLANAR: return "DSD_LSBF_PLANAR";
        case AV_CODEC_ID_DSD_MSBF_PLANAR: return "DSD_MSBF_PLANAR";
        case AV_CODEC_ID_4GV: return "4GV";
        case AV_CODEC_ID_INTERPLAY_ACM: return "INTERPLAY_ACM";
        case AV_CODEC_ID_XMA1: return "XMA1";
        case AV_CODEC_ID_XMA2: return "XMA2";
        case AV_CODEC_ID_FIRST_SUBTITLE: return "FIRST_SUBTITLE";
        case AV_CODEC_ID_TEXT: return "TEXT";
        case AV_CODEC_ID_XSUB: return "XSUB";
        case AV_CODEC_ID_SSA: return "SSA";
        case AV_CODEC_ID_MOV_TEXT: return "MOV_TEXT";
        case AV_CODEC_ID_HDMV_PGS_SUBTITLE: return "HDMV_PGS_SUBTITLE";
        case AV_CODEC_ID_DVB_TELETEXT: return "DVB_TELETEXT";
        case AV_CODEC_ID_SRT: return "SRT";
        case AV_CODEC_ID_MICRODVD: return "MICRODVD";
        case AV_CODEC_ID_EIA_608: return "EIA_608";
        case AV_CODEC_ID_JACOSUB: return "JACOSUB";
        case AV_CODEC_ID_SAMI: return "SAMI";
        case AV_CODEC_ID_REALTEXT: return "REALTEXT";
        case AV_CODEC_ID_STL: return "STL";
        case AV_CODEC_ID_SUBVIEWER1: return "SUBVIEWER1";
        case AV_CODEC_ID_SUBVIEWER: return "SUBVIEWER";
        case AV_CODEC_ID_SUBRIP: return "SUBRIP";
        case AV_CODEC_ID_WEBVTT: return "WEBVTT";
        case AV_CODEC_ID_MPL2: return "MPL2";
        case AV_CODEC_ID_VPLAYER: return "VPLAYER";
        case AV_CODEC_ID_PJS: return "PJS";
        case AV_CODEC_ID_ASS: return "ASS";
        case AV_CODEC_ID_HDMV_TEXT_SUBTITLE: return "HDMV_TEXT_SUBTITLE";
        case AV_CODEC_ID_FIRST_UNKNOWN: return "FIRST_UNKNOWN";
        case AV_CODEC_ID_IDF: return "IDF";
        case AV_CODEC_ID_OTF: return "OTF";
        case AV_CODEC_ID_SMPTE_KLV: return "SMPTE_KLV";
        case AV_CODEC_ID_DVD_NAV: return "DVD_NAV";
        case AV_CODEC_ID_TIMED_ID3: return "TIMED_ID3";
        case AV_CODEC_ID_BIN_DATA: return "BIN_DATA";
        case AV_CODEC_ID_PROBE: return "PROBE";
        case AV_CODEC_ID_MPEG2TS: return "MPEG2TS";
        case AV_CODEC_ID_MPEG4SYSTEMS: return "MPEG4SYSTEMS";
        case AV_CODEC_ID_FFMETADATA: return "FFMETADATA";
        case AV_CODEC_ID_WRAPPED_AVFRAME: return "WRAPPED_AVFRAME";
		default: return "UNKNOW";
    }
}
